### ISSUE TITLE
no going back from fastview to the normal simulation mode

### ISSUE THREAD

**Issue by discip** [smartavionics/RawMouse#14]
@smartavionics

Good morning Sir,
first and foremost thank you a lot, for having made this possible! 👍

Unfortunately I am experiencing, as stated in the caption, issues with the fastview.
Additionally button 2 is unresponsive after fastview is activated.

I am using a 'SpaceMouse Compact' with your latest release of RawMouse on Windows 10.

I already tried to use ctrl as well as enabling fastview via config.json, getting the same result.

Neither reslicing the model, nor reloading it, helps, it even gets worse.

For bypassing fastview altogether, my suggestion is to switch back to 'prepare', while in 'preview', while moving.

thank you in advance
kind regards

**Comment by smartavionics** [comment]
Hi @discip, sorry to hear you are having problems. I don't quite understand when the problem occurs. if the fastview  config value is 0 in the config file does it work as expected? i.e. it should only do fastview display while the ctrl key is held down and the mouse is moving. When the mouse is stationary or the ctrl key is released it should go back to the normal simulation mode.
When fastview is set to 1, it should only be in fastview mode when the mouse is moving. I have just tested this on Linux and it works as expected, I will check on a Windows machine soon.

**Comment by smartavionics** [comment]
I just tried it on a Windows 10 laptop and it works as expected. Are you using the most recent version? If not, please try that.

If it still doesn't work, please provide your cura.log file so I can see if there are any error messages.

**Comment by discip** [comment]
Good morning @smartavionics,
thank you for the quick reply.
Yes I got that, and it starts out, as you stated above, for **both cases** *([config 0 + ctrl + moving] and [config 1 + moving])*, but it never goes 'back to the normal simulation mode'.

**Comment by discip** [comment]
Yes I am using the latest version.

<details>
  <summary>
    <b>cura.log</b>
  </summary>

2021-04-12 11:40:47,549 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin FileLogger
2021-04-12 11:40:47,565 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] 
2021-04-12 11:40:47,565 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] Cura_SteamEngine version 4.9.0-BETA
2021-04-12 11:40:47,581 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] Copyright (C) 2020 Ultimaker
2021-04-12 11:40:47,581 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] 
2021-04-12 11:40:47,581 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] This program is free software: you can redistribute it and/or modify
2021-04-12 11:40:47,581 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] it under the terms of the GNU Affero General Public License as published by
2021-04-12 11:40:47,581 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] the Free Software Foundation, either version 3 of the License, or
2021-04-12 11:40:47,581 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] (at your option) any later version.
2021-04-12 11:40:47,596 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] 
2021-04-12 11:40:47,596 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] This program is distributed in the hope that it will be useful,
2021-04-12 11:40:47,596 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] but WITHOUT ANY WARRANTY; without even the implied warranty of
2021-04-12 11:40:47,596 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
2021-04-12 11:40:47,596 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] GNU Affero General Public License for more details.
2021-04-12 11:40:47,596 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] 
2021-04-12 11:40:47,596 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] You should have received a copy of the GNU Affero General Public License
2021-04-12 11:40:47,596 - DEBUG - [EngineErrorThread] UM.Backend.Backend._backendLog [110]: [Backend] along with this program.  If not, see <http://www.gnu.org/licenses/>.
2021-04-12 11:40:47,643 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin FirmwareUpdateChecker
2021-04-12 11:40:47,643 - DEBUG - [MainThread] UM.Backend.Backend._logSocketState [192]: Socket state changed to Connected
2021-04-12 11:40:47,643 - DEBUG - [MainThread] UM.Backend.Backend._onSocketStateChanged [181]: Backend connected on port 49674
2021-04-12 11:40:47,674 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin FirmwareUpdater
2021-04-12 11:40:47,737 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin GCodeGzReader
2021-04-12 11:40:47,768 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin GCodeGzWriter
2021-04-12 11:40:47,815 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin GCodeProfileReader
2021-04-12 11:40:47,893 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin GCodeReader
2021-04-12 11:40:47,924 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin GCodeWriter
2021-04-12 11:40:47,971 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin ImageReader
2021-04-12 11:40:48,002 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin LegacyProfileReader
2021-04-12 11:40:48,049 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin LocalContainerProvider
2021-04-12 11:40:48,112 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin LocalFileOutputDevice
2021-04-12 11:40:48,159 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin MachineSettingsAction
2021-04-12 11:40:48,205 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin ModelChecker
2021-04-12 11:40:48,252 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin MonitorStage
2021-04-12 11:40:48,299 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin PerObjectSettingsTool
2021-04-12 11:40:48,346 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin PostProcessingPlugin
2021-04-12 11:40:48,377 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin PrepareStage
2021-04-12 11:40:48,408 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin PreviewStage
2021-04-12 11:40:48,471 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin RemovableDriveOutputDevice
2021-04-12 11:40:48,502 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SentryLogger
2021-04-12 11:40:48,580 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SimulationView
2021-04-12 11:40:48,627 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SliceInfoPlugin
2021-04-12 11:40:48,674 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SolidView
2021-04-12 11:40:48,705 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SupportEraser
2021-04-12 11:40:48,940 - WARNING - [MainThread] UM.Logger.logException [112]: Exception: Failed to load packages for Marketplace
2021-04-12 11:40:48,940 - WARNING - [MainThread] UM.Logger.logException [116]: NoneType: None
2021-04-12 11:40:48,940 - WARNING - [MainThread] UM.Logger.logException [112]: Exception: Failed to load packages for Marketplace
2021-04-12 11:40:48,940 - WARNING - [MainThread] UM.Logger.logException [116]: NoneType: None
2021-04-12 11:40:48,940 - WARNING - [MainThread] UM.Logger.logException [112]: Exception: Failed to load packages for Marketplace
2021-04-12 11:40:48,940 - WARNING - [MainThread] UM.Logger.logException [116]: NoneType: None
2021-04-12 11:40:48,940 - WARNING - [MainThread] UM.Logger.logException [112]: Exception: Failed to load packages for Marketplace
2021-04-12 11:40:48,955 - WARNING - [MainThread] UM.Logger.logException [116]: NoneType: None
2021-04-12 11:40:48,955 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin Toolbox
2021-04-12 11:40:49,002 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin CameraTool
2021-04-12 11:40:49,049 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin MirrorTool
2021-04-12 11:40:49,111 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin RotateTool
2021-04-12 11:40:49,174 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin ScaleTool
2021-04-12 11:40:49,221 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin SelectionTool
2021-04-12 11:40:49,268 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin TranslateTool
2021-04-12 11:40:49,299 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin TrimeshReader
2021-04-12 11:40:49,346 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin UFPReader
2021-04-12 11:40:49,393 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin UFPWriter
2021-04-12 11:40:49,439 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin UltimakerMachineActions
2021-04-12 11:40:50,158 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin UM3NetworkPrinting
2021-04-12 11:40:50,205 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin UpdateChecker
2021-04-12 11:40:50,205 - INFO - [Thread-1] UpdateChecker.UpdateCheckerJob.run [40]: Checking for new version of cura
2021-04-12 11:40:50,330 - WARNING - [Thread-1] UM.Logger.logException [112]: Exception: Failed to check for new version: <urlopen error [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen>
2021-04-12 11:40:50,330 - WARNING - [Thread-1] UM.Logger.logException [116]: Traceback (most recent call last):
2021-04-12 11:40:50,346 - WARNING - [Thread-1] UM.Logger.logException [116]:   File "urllib\request.py", line 1354, in do_open
2021-04-12 11:40:50,346 - WARNING - [Thread-1] UM.Logger.logException [116]:   File "http\client.py", line 1255, in request
2021-04-12 11:40:50,346 - WARNING - [Thread-1] UM.Logger.logException [116]:   File "http\client.py", line 1301, in _send_request
2021-04-12 11:40:50,346 - WARNING - [Thread-1] UM.Logger.logException [116]:   File "http\client.py", line 1250, in endheaders
2021-04-12 11:40:50,361 - WARNING - [Thread-1] UM.Logger.logException [116]:   File "http\client.py", line 1010, in _send_output
2021-04-12 11:40:50,361 - WARNING - [Thread-1] UM.Logger.logException [116]:   File "http\client.py", line 950, in send
2021-04-12 11:40:50,361 - WARNING - [Thread-1] UM.Logger.logException [116]:   File "http\client.py", line 1424, in connect
2021-04-12 11:40:50,361 - WARNING - [Thread-1] UM.Logger.logException [116]:   File "ssl.py", line 500, in wrap_socket
2021-04-12 11:40:50,361 - WARNING - [Thread-1] UM.Logger.logException [116]:   File "ssl.py", line 1040, in _create
2021-04-12 11:40:50,377 - WARNING - [Thread-1] UM.Logger.logException [116]:   File "ssl.py", line 1309, in do_handshake
2021-04-12 11:40:50,377 - WARNING - [Thread-1] UM.Logger.logException [116]: ConnectionResetError: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen
2021-04-12 11:40:50,377 - WARNING - [Thread-1] UM.Logger.logException [116]: 
2021-04-12 11:40:50,377 - WARNING - [Thread-1] UM.Logger.logException [116]: During handling of the above exception, another exception occurred:
2021-04-12 11:40:50,377 - WARNING - [Thread-1] UM.Logger.logException [116]: 
2021-04-12 11:40:50,377 - WARNING - [Thread-1] UM.Logger.logException [116]: Traceback (most recent call last):
2021-04-12 11:40:50,392 - WARNING - [Thread-1] UM.Logger.logException [116]:   File "C:\Program Files\Ultimaker Cura 4.9.0\plugins\UpdateChecker\UpdateCheckerJob.py", line 48, in run
2021-04-12 11:40:50,392 - WARNING - [Thread-1] UM.Logger.logException [116]:     latest_version_file = urllib.request.urlopen(request, context = context)
2021-04-12 11:40:50,392 - WARNING - [Thread-1] UM.Logger.logException [116]:   File "urllib\request.py", line 222, in urlopen
2021-04-12 11:40:50,392 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin USBPrinting
2021-04-12 11:40:50,392 - WARNING - [Thread-1] UM.Logger.logException [116]:   File "urllib\request.py", line 525, in open
2021-04-12 11:40:50,392 - WARNING - [Thread-1] UM.Logger.logException [116]:   File "urllib\request.py", line 542, in _open
2021-04-12 11:40:50,408 - WARNING - [Thread-1] UM.Logger.logException [116]:   File "urllib\request.py", line 502, in _call_chain
2021-04-12 11:40:50,408 - WARNING - [Thread-1] UM.Logger.logException [116]:   File "urllib\request.py", line 1397, in https_open
2021-04-12 11:40:50,408 - WARNING - [Thread-1] UM.Logger.logException [116]:   File "urllib\request.py", line 1357, in do_open
2021-04-12 11:40:50,408 - WARNING - [Thread-1] UM.Logger.logException [116]: urllib.error.URLError: <urlopen error [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen>
2021-04-12 11:40:50,486 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade21to22
2021-04-12 11:40:50,533 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade22to24
2021-04-12 11:40:50,595 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade25to26
2021-04-12 11:40:50,627 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade26to27
2021-04-12 11:40:50,674 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade27to30
2021-04-12 11:40:50,720 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade30to31
2021-04-12 11:40:50,767 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade32to33
2021-04-12 11:40:50,814 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade33to34
2021-04-12 11:40:50,861 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade34to35
2021-04-12 11:40:50,908 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade35to40
2021-04-12 11:40:50,955 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade40to41
2021-04-12 11:40:50,986 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade41to42
2021-04-12 11:40:51,033 - INFO - [MainThread] UM.Logger.info [128]: Loaded plugin VersionUpgrade42to43
2021-04-12 11:40:

</details>

**Comment by smartavionics** [comment]
Thanks but I need more of the log file than that snippet. Can you please zip the whole file and attach to this issue, thanks.

**Comment by discip** [comment]
Sorry I did not realize it was not the whole content.
[cura.txt.zip](https://github.com/smartavionics/RawMouse/files/6357156/cura.txt.zip)

**Comment by smartavionics** [comment]
Thanks for the complete log file. I can see from that there are some problems. I wonder if your RawMouse installation is correct. Under the plugins directory you should have a top-level RawMouse directory (with possibly a version suffix, i.e. RawMouse-1.1.0) and then inside that directory you should have RawMouse and FastView sub-directories which contain various files. Do you see that?

**Comment by discip** [comment]
Ah, yes, that was part of the failure. But it seems there is more to it, since now it initially switches to prepare mode when moved, but every other move is performed in  preview mode. No matter if configured in json or holding ctrl. At the end of these moves it changes to fastview for a fraction of a second.
[cura.zip](https://github.com/smartavionics/RawMouse/files/6357954/cura.zip)
thank you in advance

**Comment by smartavionics** [comment]
Wow, it looks really confused! I don't understand what's going on there at all. I do note that you are using some other plugins and I wonder if there is some interaction. Can you please try disabling the sidebar gui and startup optimiser plugins and anything else that could be affecting the GUI?

**Comment by discip** [comment]
@smartavionics
You were right about the *sidebar gui* beeing the culprit. 😃
If I am right, it would help to make the view switch to *prepare mode*, instead of switching to *fastview*, since the movement in *prepare mode* seems to be as fast as in fastview (imho).
thanks
regards

**Comment by smartavionics** [comment]
Yes, the movement speed in prepare mode is similar to fastview but it takes a bit more more time to switch to prepare mode and I wanted to use the minimum number of API calls to make the switch. Perhaps @fieldOfView can shed some light on why the sidebar gui is interfering with rawmouse (or vice-versa).

**Comment by fieldOfView** [comment]
I have no idea what "fastview" is. Can anyone clue me in?

**Comment by smartavionics** [comment]
It's a minimal view that the rawmouse plugin switches to when the spacemouse is being used. The idea is that because the normal simulation view takes so long to redraw switching to fastview makes the display update much quicker and that gives smoother motion. It's a crude hack around the poor performance of the simulation view on slow computers and when the model has more than a small number of lines. I'm using a separate view so as to avoid having to switch the stage so as to be able to use the SolidView.

**Comment by discip** [comment]
Well I'll leave this to you guys, since you are the knowledgeable ones.
But I would like to see both plugins working alongside, since these are much appreciated!
## Thank you in advance! 😁

**Comment by smartavionics** [comment]
Does the sidebar gui call setActiveStage() and/or setActiveView()?

**Comment by fieldOfView** [comment]
One of the things the Sidebar GUI does is change how the XRay view is stuffed away inside the Preview tab (because it does not belong there; it makes no sense having it there). In doing so, it makes changes to how views are selected, and I can imagine that breaks when other plugins start to get creative with views too.

If someone opens an issue to improve interoperability with this plugin at the SidebarGUI issuequeue, I'll dust off my spacemouse and look in to it next week. 
https://github.com/fieldOfView/Cura-SidebarGUIPlugin/issues

**Comment by smartavionics** [comment]
I remember now, I can't use SolidView because, for some unknown reason, if I switch to that with the preview stage selected, one of the drop down menus at the top of the view is missing.

I agree that it's bonkers to have the xray view associated with the preview stage.

I will open an issue as you suggest and perhaps we can get the plugins to live happily together.
